In [1]:
# Rohit Agrawal
# 1610110292
# MAT492 - Data Mining and its Applications

import numpy as np

word1 = "intention"
word2 = "execution"
word1length = len(word1)
word2length = len(word2)

# Add '#' to each word to form the Edit matrix
word1list = list(word1)[::-1]
word1list.append('#')
word1list = word1list[::-1]
word2list = list(word2)[::-1]
word2list.append('#')
word2list = word2list[::-1]

EDmatrix = np.zeros((word1length + 1, word2length + 1))
EDmatrix[:,0] = np.arange(word1length+1)[::-1]
EDmatrix[-1,:] = np.arange(word2length+1)
print('Edit Distance Matrix = \n' + str(EDmatrix))

Edit Distance Matrix = 
[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [8. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [7. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]


In [2]:
# Compute all distances for each entry in the EDmatrix and fill it with the one thats the minimum 
for i in range(0,EDmatrix.shape[0]-1)[::-1]:
    for j in range(1, EDmatrix.shape[1]):
        print('i = ' + str(i) + ', j = ' + str(j))
        dist1 = EDmatrix[i+1,j] + 1
        dist2 = EDmatrix[i,j-1] + 1
        dist3 = EDmatrix[i+1,j-1]
        print('Comparing characters ' + str(word1list[EDmatrix.shape[0] - i - 1]) + ' and ' + str(word2list[j]))
        if word1list[EDmatrix.shape[0] - i - 1] == word2list[j]:
            dist3 += 0
        else:
            dist3 += 2
        print('Distance 1 = ' + str(dist1) + '\n')
        print('Distance 2 = ' + str(dist2) + '\n')
        print('Distance 3 = ' + str(dist3) + '\n')
        EDmatrix[i,j] = min([dist1, dist2, dist3])

i = 8, j = 1
Comparing characters i and e
Distance 1 = 2.0

Distance 2 = 2.0

Distance 3 = 2.0

i = 8, j = 2
Comparing characters i and x
Distance 1 = 3.0

Distance 2 = 3.0

Distance 3 = 3.0

i = 8, j = 3
Comparing characters i and e
Distance 1 = 4.0

Distance 2 = 4.0

Distance 3 = 4.0

i = 8, j = 4
Comparing characters i and c
Distance 1 = 5.0

Distance 2 = 5.0

Distance 3 = 5.0

i = 8, j = 5
Comparing characters i and u
Distance 1 = 6.0

Distance 2 = 6.0

Distance 3 = 6.0

i = 8, j = 6
Comparing characters i and t
Distance 1 = 7.0

Distance 2 = 7.0

Distance 3 = 7.0

i = 8, j = 7
Comparing characters i and i
Distance 1 = 8.0

Distance 2 = 8.0

Distance 3 = 6.0

i = 8, j = 8
Comparing characters i and o
Distance 1 = 9.0

Distance 2 = 7.0

Distance 3 = 9.0

i = 8, j = 9
Comparing characters i and n
Distance 1 = 10.0

Distance 2 = 8.0

Distance 3 = 10.0

i = 7, j = 1
Comparing characters n and e
Distance 1 = 3.0

Distance 2 = 3.0

Distance 3 = 3.0

i = 7, j = 2
Comparing characters n an

In [3]:
# Computed Edit Distance Matrix
print('Edit Distance Matrix = \n' + str(EDmatrix) + '\n')
print('-------------------------------------\n')

# Number of operations 
print("Optimal number of operations needed = " + str(EDmatrix[0 , EDmatrix.shape[1] - 1]) + '\n')
print('-------------------------------------\n')

# Optimal path
print('Optimal path -> \n')
i = 0
j = EDmatrix.shape[1] - 1
while(j>=0 and i<EDmatrix.shape[0]):
    print('(' + str(i) + ',' + str(j) + ')')
    curr_val = EDmatrix[i, j] 
    dist1 = EDmatrix[i, j-1] 
    if(i == EDmatrix.shape[0] - 1):      # If path is at the edge of the matrix, we simply move to the only block available to us
        j = j-1
        continue
    else:
        dist2 = EDmatrix[i+1, j]
        dist3 = EDmatrix[i+1, j-1]
    
    idx = np.argmin([dist1, dist2, dist3])          # Find which distance is the minimum
    if idx == 0:
        j = j-1
    if idx == 1:
        i = i+1
    if idx == 2:
        i = i+1
        j = j-1
print('\n-------------------------------------\n')

# Step by step operations
testword = word1list
i = 0
j = EDmatrix.shape[1] - 1
n = EDmatrix.shape[0] - 1

counter = 1
print('Step by step operations -> \n')
while(j>=0 and i<EDmatrix.shape[0]):
    curr_val = EDmatrix[i, j] 
    dist1 = EDmatrix[i, j-1] 
    if(i == EDmatrix.shape[0] - 1):
        j = j-1
        if(EDmatrix[i][j] == curr_val):
            #print(str(counter) + '. No Change \n')
            #counter += 1
            continue
        else:
            if word2list[j+1] is not '#':
                print(str(counter) + '. Insert ' + str(word2list[j+1]) + '\n')
                counter += 1
        continue
    else:
        dist2 = EDmatrix[i+1, j]
        dist3 = EDmatrix[i+1, j-1]
    
    idx = np.argmin([dist1, dist2, dist3])
    if idx == 0:
        j = j-1
        if(EDmatrix[i][j] == curr_val):
            #print(str(counter) + '. No Change \n')
            #counter += 1
            continue
        else:
            print(str(counter) + '. Insert ' + str(word2list[j+1]) + '\n')
            counter += 1
    if idx == 1:
        i = i+1
        if(EDmatrix[i][j] == curr_val):
            #print(str(counter) + '. No Change \n')
            #counter += 1
            continue
        else:
            print(str(counter) + '. Delete ' + str(testword[n-i+1]) + '\n')
            counter += 1
    if idx == 2:
        i = i+1
        j = j-1
        if(EDmatrix[i][j] == curr_val):
            #print(str(counter) + '. No Change \n')
            #counter += 1
            continue
        else:
            print(str(counter) + '. Substitute ' + str(testword[n-i+1]) + ' with ' + str(word2list[j+1]) + ' \n')
            counter += 1

print('-------------------------------------\n')
print('Original string - ' + str(word1) + '\n')
print('Final string - ' + str(word2) + '\n')

Edit Distance Matrix = 
[[ 9.  8.  9. 10. 11. 12. 11. 10.  9.  8.]
 [ 8.  7.  8.  9. 10. 11. 10.  9.  8.  9.]
 [ 7.  6.  7.  8.  9. 10.  9.  8.  9. 10.]
 [ 6.  5.  6.  7.  8.  9.  8.  9. 10. 11.]
 [ 5.  4.  5.  6.  7.  8.  9. 10. 11. 10.]
 [ 4.  3.  4.  5.  6.  7.  8.  9. 10.  9.]
 [ 3.  4.  5.  6.  7.  8.  7.  8.  9.  8.]
 [ 2.  3.  4.  5.  6.  7.  8.  7.  8.  7.]
 [ 1.  2.  3.  4.  5.  6.  7.  6.  7.  8.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]]

-------------------------------------

Optimal number of operations needed = 8.0

-------------------------------------

Optimal path -> 

(0,9)
(1,8)
(2,7)
(3,6)
(4,5)
(5,4)
(5,3)
(5,2)
(5,1)
(6,0)
(7,0)
(8,0)
(9,0)

-------------------------------------

Step by step operations -> 

1. Substitute n with u 

2. Insert c

3. Insert e

4. Insert x

5. Delete t

6. Delete n

7. Delete i

-------------------------------------

Original string - intention

Final string - execution

