In [1]:
# Rohit Agrawal
# 1610110292
# MAT492 - Data Mining and its Applications

import numpy as np
def rmse(a,b):
    error = 0
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            error += (a[i][j] - b[i][j])**2
    error = error/len(a)
    error = np.sqrt(error)
    return error

In [2]:
n = 5
d = 2
M = np.random.randint(5, size=(n,n))
print('M = ' + str(M))

M = [[4 3 3 2 3]
 [3 1 4 1 1]
 [2 0 2 1 3]
 [0 3 2 3 2]
 [0 2 2 1 3]]


#### Optimizing elements sequentially

In [3]:
# Initializing as ones
U = np.ones((n,d))
V = np.ones((d,n))
P = np.matmul(U,V)
current_rmse = rmse(P,M)
print('Original RMSE = ' + str(current_rmse) + '\n')

num_iterations = 1000
for iteration in range(num_iterations):
    for r in range(n):         # Optimizing U matrix
        for s in range(d):
            numerator = 0
            denominator = 0
            for j in range(d):
                temp = 0
                for k in range(d):
                    if k is not s:
                        temp += U[r][k]*V[k][j]
                numerator += V[s][j] * (M[r][j] - temp)
                denominator += V[s][j]**2
            optimal = numerator/denominator
            U[r][s] = optimal
            P = np.matmul(U,V)
            #print('Changing element - U[' + str(r) +'][' + str(s) + '] :')
            #print('U = ' + str(U) + '\n')
            #print('RMSE: ' + str(rmse(P,M)) + '\n')

    for s in range(n):          # Optimizing V matrix
        for r in range(d):
            numerator = 0
            denominator = 0
            for i in range(n):
                temp = 0
                for k in range(d):
                    if k is not r:
                        temp += U[i][k]*V[k][s]
                numerator += U[i][r] * (M[i][s] - temp)
                denominator += U[i][r]**2
            optimal = numerator/denominator
            V[r][s] = optimal
            P = np.matmul(U,V)
            #print('Changing element - V[' + str(r) +'][' + str(s) + '] :')
            #print('V = ' + str(V) + '\n')
            #print('RMSE: ' + str(rmse(P,M)) + '\n')
print('RMSE: ' + str(rmse(P,M)) + '\n')

Original RMSE = 2.569046515733026

RMSE: 1.771442646481606



In [4]:
# Initializing using optimal initialization
a = np.mean(M)
optimal_init = np.sqrt(a/d)
U = np.full((n,d), optimal_init)
V = np.full((d,n), optimal_init)
P = np.matmul(U,V)
current_rmse = rmse(P,M)
print('Original RMSE = ' + str(current_rmse) + '\n')

num_iterations = 1000
for iteration in range(num_iterations):
    for r in range(n):         # Optimizing U matrix
        for s in range(d):
            numerator = 0
            denominator = 0
            for j in range(d):
                temp = 0
                for k in range(d):
                    if k is not s:
                        temp += U[r][k]*V[k][j]
                numerator += V[s][j] * (M[r][j] - temp)
                denominator += V[s][j]**2
            optimal = numerator/denominator
            U[r][s] = optimal
            P = np.matmul(U,V)
            #print('Changing element - U[' + str(r) +'][' + str(s) + '] :')
            #print('U = ' + str(U) + '\n')
            #print('RMSE: ' + str(rmse(P,M)) + '\n')

    for s in range(n):          # Optimizing V matrix
        for r in range(d):
            numerator = 0
            denominator = 0
            for i in range(n):
                temp = 0
                for k in range(d):
                    if k is not r:
                        temp += U[i][k]*V[k][s]
                numerator += U[i][r] * (M[i][s] - temp)
                denominator += U[i][r]**2
            optimal = numerator/denominator
            V[r][s] = optimal
            P = np.matmul(U,V)
            #print('Changing element - V[' + str(r) +'][' + str(s) + '] :')
            #print('V = ' + str(V) + '\n')
            #print('RMSE: ' + str(rmse(P,M)) + '\n')
print('RMSE: ' + str(rmse(P,M)) + '\n')

Original RMSE = 2.5674890457409942

RMSE: 1.7714426464816058



In [5]:
print('M = ' + str(M) + '\n')
print('P = ' + str(P) )

M = [[4 3 3 2 3]
 [3 1 4 1 1]
 [2 0 2 1 3]
 [0 3 2 3 2]
 [0 2 2 1 3]]

P = [[ 4.00000000e+00  3.00000000e+00  4.38235294e+00  2.48190045e+00
   3.57692308e+00]
 [ 3.00000000e+00  1.00000000e+00  2.58823529e+00  9.36651584e-01
   1.76923077e+00]
 [ 2.00000000e+00  9.57783877e-17  1.35294118e+00  1.31221719e-01
   6.92307692e-01]
 [-2.75127389e-18  3.00000000e+00  1.67647059e+00  2.21945701e+00
   2.19230769e+00]
 [-2.05653063e-17  2.00000000e+00  1.11764706e+00  1.47963801e+00
   1.46153846e+00]]


#### Optimizing random elements


In [6]:
# Initializing as ones
U = np.ones((n,d))
V = np.ones((d,n))
P = np.matmul(U,V)
current_rmse = rmse(P,M)
print('Original RMSE = ' + str(current_rmse) + '\n')

num_iterations = 1000
for iteration in range(num_iterations):
    #print('Iteration ' + str(iteration) + ': \n')
    optimizeUorV = np.random.randint(2)
    if optimizeUorV == 0:         # Optimize U matrix
        r = np.random.randint(n)
        s = np.random.randint(d)
        numerator = 0
        denominator = 0
        for j in range(d):
            temp = 0
            for k in range(d):
                if k is not s:
                    temp += U[r][k]*V[k][j]
            numerator += V[s][j] * (M[r][j] - temp)
            denominator += V[s][j]**2
        optimal = numerator/denominator
        U[r][s] = optimal
        P = np.matmul(U,V)
        #print('Changing element - U[' + str(r) +'][' + str(s) + '] :')
        #print('U = ' + str(U) + '\n')
        #print('RMSE: ' + str(rmse(P,M)) + '\n')

    else:                         # Optimize V matrix
        r = np.random.randint(d)
        s = np.random.randint(n)
        numerator = 0
        denominator = 0
        for i in range(n):
            temp = 0
            for k in range(d):
                if k is not r:
                    temp += U[i][k]*V[k][s]
            numerator += U[i][r] * (M[i][s] - temp)
            denominator += U[i][r]**2
        optimal = numerator/denominator
        V[r][s] = optimal
        P = np.matmul(U,V)
        #print('Changing element - V[' + str(r) +'][' + str(s) + '] :')
        #print('V = ' + str(V) + '\n')
        #print('RMSE: ' + str(rmse(P,M)) + '\n')
print('RMSE: ' + str(rmse(P,M)) + '\n')

Original RMSE = 2.569046515733026

RMSE: 1.7714426464814454



In [7]:
# Initializing using optimal initialization
a = np.mean(M)
optimal_init = np.sqrt(a/d)
U = np.full((n,d), optimal_init)
V = np.full((d,n), optimal_init)
P = np.matmul(U,V)
current_rmse = rmse(P,M)
print('Original RMSE = ' + str(current_rmse) + '\n')

num_iterations = 1000
for iteration in range(num_iterations):
    #print('Iteration ' + str(iteration) + ': \n')
    optimizeUorV = np.random.randint(2)
    if optimizeUorV == 0:         # Optimize U matrix
        r = np.random.randint(n)
        s = np.random.randint(d)
        numerator = 0
        denominator = 0
        for j in range(d):
            temp = 0
            for k in range(d):
                if k is not s:
                    temp += U[r][k]*V[k][j]
            numerator += V[s][j] * (M[r][j] - temp)
            denominator += V[s][j]**2
        optimal = numerator/denominator
        U[r][s] = optimal
        P = np.matmul(U,V)
        #print('Changing element - U[' + str(r) +'][' + str(s) + '] :')
        #print('U = ' + str(U) + '\n')
        #print('RMSE: ' + str(rmse(P,M)) + '\n')

    else:         # Optimize V matrix
        r = np.random.randint(d)
        s = np.random.randint(n)
        numerator = 0
        denominator = 0
        for i in range(n):
            temp = 0
            for k in range(d):
                if k is not r:
                    temp += U[i][k]*V[k][s]
            numerator += U[i][r] * (M[i][s] - temp)
            denominator += U[i][r]**2
        optimal = numerator/denominator
        V[r][s] = optimal
        P = np.matmul(U,V)
        #print('Changing element - V[' + str(r) +'][' + str(s) + '] :')
        #print('V = ' + str(V) + '\n')
        #print('RMSE: ' + str(rmse(P,M)) + '\n')
print('RMSE: ' + str(rmse(P,M)) + '\n')

Original RMSE = 2.5674890457409942

RMSE: 1.771442646481611



In [8]:
print('M = ' + str(M) + '\n')
print('P = ' + str(P) )

M = [[4 3 3 2 3]
 [3 1 4 1 1]
 [2 0 2 1 3]
 [0 3 2 3 2]
 [0 2 2 1 3]]

P = [[ 4.00000000e+00  3.00000000e+00  4.38235294e+00  2.48190045e+00
   3.57692308e+00]
 [ 3.00000000e+00  1.00000000e+00  2.58823529e+00  9.36651584e-01
   1.76923077e+00]
 [ 2.00000000e+00 -4.20660360e-14  1.35294118e+00  1.31221719e-01
   6.92307692e-01]
 [ 9.73846673e-14  3.00000000e+00  1.67647059e+00  2.21945701e+00
   2.19230769e+00]
 [ 6.77132713e-14  2.00000000e+00  1.11764706e+00  1.47963801e+00
   1.46153846e+00]]
